osx_image: xcode8.3
language: objective-c
podfile: Demo/Podfile
cache: cocoapods
before_install:
  - pod repo update

script: cd Demo ; set -o pipefail && xcodebuild -workspace 'Demo.xcworkspace' -scheme 'Demo' -configuration 'Debug' -sdk iphonesimulator -destination 'name=iPhone 6s' build test  | xcpretty -c --test
